# Slicing Practice


In [2]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [4]:
print('shape' ,arr.shape)
print(arr.ndim)

shape (3, 3, 3)
3


##### 1. Extract the frist matrix (all row, all column of the frist layer)

In [64]:
arr[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### 2. Extract the Second matrix

In [65]:
arr[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

##### 3.Extract the top-left 2*2 submatrix from the third matrix

In [47]:
arr[2,0:2,0:2]

array([[19, 20],
       [22, 23]])

##### 4. Extract the middle column of all matrix

In [42]:
arr[:3,:,1:2]

array([[[ 2],
        [ 5],
        [ 8]],

       [[11],
        [14],
        [17]],

       [[20],
        [23],
        [26]]])

##### 5. Extract all element from the frist row of all matrix

In [77]:
arr[:3,0,0:]

array([[ 1,  2,  3],
       [10, 11, 12],
       [19, 20, 21]])

In [53]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

##### 6. Extract the last column from the second row of all matrices

In [60]:
arr[:3,1,-1]

array([ 6, 15, 24])

##### 7. Extract the frist element of the frist row of all matrices

In [62]:
arr[:3,0,0]

array([ 1, 10, 19])